services:
  web:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=odoo
      - DATABASE_PASSWORD=123

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
