services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - C:/Users/diazs/DAM2/OdooPracticas/Tarea14/addons:/mnt/extra-addons
      - C:/Users/diazs/DAM2/OdooPracticas/Tarea14/config:/etc/odoo

volumes:
  odoo-web-data:
  odoo-db-data: